### ISSUE TITLE
strokeCap / strokeLinecap

### ISSUE THREAD

**Issue by jcsmesquita** [magicismight/react-native-art-svg#11]
Hi!

I'm trying to get strokeCap working with Android on this package's version 1.1.1.

Any idea if it's an issue with ART not supporting this yet?

**Comment by magicismight** [comment]
We use `strokeLinecap` instead of `strokeCap`.
Because `stroke-linecap` is a valid svg attribute not stroke-cap.
And it is supported on `react-native-svg@1.1.0` both android and iOS.

**Comment by magicismight** [comment]
BTW
This package has changed name to `react-native-svg` now.
And it is no longer based on ReactNativeART

**Comment by jcsmesquita** [comment]
Hey thanks for the feedback. I upgraded to react-native-svg but had to manually install the "art" npm module. It's not very clear in the instructions that it is needed. Also I've made a pull request because patternReg.js was missing.

The linecaps are default to square now, but I'm still not able to change them with the <Line> component. 😞

**Comment by magicismight** [comment]
Which `react-native-svg` version did you installed?
 And did you install by npm2? or npm3?

**Comment by jcsmesquita** [comment]
react-native-svg@1.1.0 and npm2 (2.14.7)

**Comment by magicismight** [comment]
![qq 20160423215027](https://cloud.githubusercontent.com/assets/7693239/14761888/3384085a-099f-11e6-9aa9-1bff0e60d893.png)

strokeLinecap works fine on android.
You can try the example code.
```
import Svg, {
    Path,
    Rect,
    G,
    Defs,
    Stop,
    RadialGradient,
    Polyline,
    ClipPath,
    Circle,
    Text
} from 'react-native-svg';

<Svg height="80" width="225">
            <G fill="none" stroke="black" strokeWidth="4">
                <Path strokeDasharray="5,5" d="M5 20 l215 0" />
                <Path strokeDasharray="10,10" d="M5 40 l215 0" />
                <Path strokeDasharray="20,10,5,5,5,10" d="M5 60 l215 0" />
            </G>
</Svg>
```

Maybe you imported the elements from the old `react-native-art-svg` instead of `react-native-svg`?

**Comment by jcsmesquita** [comment]
I think the issue is with the <Line> component, I tried using path and it works!

**Comment by magicismight** [comment]
Which component did you used?
And the `art` module issue is fixed by now,
Thx for reporting this to me.
I will release those fixes to npm by next Monday.

**Comment by jcsmesquita** [comment]
It's the `<Line>`component.
I'm glad to help, by the way great job on this package!

**Comment by magicismight** [comment]
I will fix this soon.

**Comment by magicismight** [comment]
Good find!
:+1: 
Get it be fixed in [last commit](https://github.com/magicismight/react-native-art-svg/commit/1741f63b41d365024191e3819334411e4d5dcbec)

**Comment by vadermemo** [comment]
@magicismight  This is June, 2018 and the snippet

<Line
            x1={0}
            x2={100}
            y1={0}
            y2={0}
            stroke="black"
            strokeWidth={2}
            strokeLinecap="round"    // < ---- doesn't work
            />

Doesn't work!

**Comment by raymondxie** [comment]
This is Nov. 2023, with react-native-svg@13.10.0, the `strokeLinecap="round"` still does not work for <Line> or <Path>

**Comment by federicochileserawfish** [comment]
react-native-svg@15.1.0 still doesn't work. Any news?
